### ISSUE TITLE
 Update DNS, so that https://malmorb.se/ shows no DNS warnings

### ISSUE THREAD

**Issue by olleolleolle** [malmorb/malmorb.github.com#52]

**Comment by smgt** [comment]
I'm taking a look at this.

**Comment by smgt** [comment]
It seems that they have updated the A record ips for apex domains. I've updated malmorb.se A record to point the new domains. Found some information about this deep in their documentation. https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

The TTL for malmorb.se is 3600 seconds so I guess this will be fixed in about 56min from now (since everyone is strict about DNS TTL).

**Comment by olleolleolle** [comment]
Thanks so much!
